#!/usr/bin/env node
'use strict';
/*
 * build_manual.js — regenerate docs/assets/manual.js from docs/USER_MANUAL.md.
 *
 * WHY THIS EXISTS:
 *   docs/USER_MANUAL.md is the SINGLE editable source of truth for the
 *   dispatcher manual. The in-app viewer (docs/help.html) renders that content
 *   with a vendored markdown library. On https / a local server help.html can
 *   fetch() USER_MANUAL.md directly. But browsers block fetch() of a file://
 *   sibling (same reason dispatcher.html notes for its JSON), so the offline /
 *   double-click path needs the markdown delivered as a <script>, not a fetch.
 *
 *   This script wraps the raw markdown into docs/assets/manual.js as a string on
 *   window.WildlifeManual. It produces NO second hand-edited copy: editors edit
 *   ONLY the .md and re-run `node tools/build_manual.js`. help.html prefers the
 *   live fetch and only falls back to this embedded copy on file://.
 *
 * USAGE:  node tools/build_manual.js
 */
const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const SRC = path.join(ROOT, 'docs', 'USER_MANUAL.md');
const OUT = path.join(ROOT, 'docs', 'assets', 'manual.js');

const md = fs.readFileSync(SRC, 'utf8');

// JSON.stringify gives a safe, fully-escaped JS string literal (quotes,
// newlines, backslashes, unicode all handled) — no fragile manual escaping.
const banner =
  '/* AUTO-GENERATED by tools/build_manual.js from docs/USER_MANUAL.md.\n' +
  ' * DO NOT EDIT BY HAND. Edit docs/USER_MANUAL.md, then run:\n' +
  ' *   node tools/build_manual.js\n' +
  ' * Provides window.WildlifeManual.markdown (file:// fallback for help.html). */\n';

const body =
  '(function (root) {\n' +
  '  "use strict";\n' +
  '  root.WildlifeManual = { markdown: ' + JSON.stringify(md) + ' };\n' +
  '})(typeof window !== "undefined" ? window : this);\n';

fs.writeFileSync(OUT, banner + body, 'utf8');
console.log('Wrote ' + path.relative(ROOT, OUT) + ' (' + md.length + ' chars of markdown).');
